# Generated by Django 3.0.5 on 2020-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0002_auto_20200501_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='approx_questions',
            field=models.IntegerField(default=0),
        ),
    ]
