# Generated by Django 3.0.5 on 2020-05-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0004_quiz_negative_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='approx_questions',
            field=models.IntegerField(),
        ),
    ]
