# Generated by Django 3.0.5 on 2020-05-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(default='null', max_length=20, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='usn',
            field=models.CharField(default='null', max_length=15, verbose_name='usn'),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=0, verbose_name='year'),
        ),
    ]
